# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumtrapzRcpp <- function(X, Y) {
    .Call('_fdadensity_cumtrapzRcpp', PACKAGE = 'fdadensity', X, Y)
}

trapzRcpp <- function(X, Y) {
    .Call('_fdadensity_trapzRcpp', PACKAGE = 'fdadensity', X, Y)
}

